ARG BASE

FROM $BASE

ARG AUTHOR
ARG VERSION

LABEL maintainer=$AUTHOR version=$VERSION

ARG TARGETOS
ARG TARGETARCH

ADD ./.tmp/$TARGETARCH/dockerd /usr/local/bin/dockerd
ADD ./.tmp/$TARGETARCH/docker-proxy /usr/local/bin/docker-proxy
